import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter , Allura } from "next/font/google";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const inter = Inter({
  weight: "400",
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const allura = Allura({
  weight: "400",
  variable: "--font-allura-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} ${allura.variable} antialiased px-8`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
